kotlin.code.style=official
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.1
minecraft_version_range=[26.1.1]
neo_version=26.1.1.10-beta
loader_version_range=[6,)

mod_id=aaron
mod_name=Aaron
mod_license=MIT
mod_version=1.10.0
mod_group_id=dev.aaronhowser.mods
mod_authors=aaronhowser1
mod_description=My library

kff_version=6.2.0
kff_version_range=[6.2.0,)

curseforge_id=1384284
modrinth_id=usfxOp9L